# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
             
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Build HTML
        run: | 
          cd docs/
          make html    
      - name: Deploy ftp
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          port: 2222
          ftp-server: ${{ secrets.STAGING_FTP_URL }}
          ftp-username: ${{ secrets.STAGING_FTP_USER }}
          ftp-password: ${{ secrets.STAGING_FTP_PASSWORD }}
          server-dir: ${{ secrets.STAGING_FTP_DIR }}
          local-dir: docs/build/html/
